name: weather
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - eccodes
  - cfgrib
  - xarray
  - netcdf4
  - dask
  - matplotlib
  - cartopy
  - metpy          # Skew-T plots
  - pillow
  - cdsapi
  - pip
  - pip:
      - ai-models
      - ai-models-fourcastnetv2
      - ai-models-panguweather
      - fastapi
      - uvicorn
